[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alpha-quest-editor"
version = "0.9.5a0"
description = "Editor desktop visual externo para FTB Quests com suporte SNBT/JSON5"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "PySide6>=6.7,<7",
  "Pillow>=10,<12",
]

[project.scripts]
alpha-quest-editor = "alphaquest.app:main"

[tool.setuptools.packages.find]
include = ["alphaquest*"]
